services:  
  learn-dl:
    image: nvcr.io/nvidia/tensorflow:25.02-tf2-py3
    container_name: learn-dl
    restart: unless-stopped
    volumes:
      - D:/Github/tf-notebooks:/app
    working_dir: /app
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]